version: '3.8'

services:
  apache:
    build: ./server/
    container_name: apache-server
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: "0.1"      # Limita o uso de CPU para 10%
          memory: "7MB"    # Limita a RAM para 6 MB
    restart: 'no'
